services:
  - name: chatbot-backend
    type: web
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 main:app
    envVars:
      - key: PORT
        value: 5000
